name: Deploy Site to Server

on: [push]

jobs:
  build:
    name: Build the site
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'
    - run: npm install
    - run: npm run build
      env:
        gc_type: ${{ secrets.gc_type }}
        gc_project_id: ${{ secrets.gc_project_id }}
        gc_private_key_id: ${{ secrets.gc_private_key_id }}
        gc_private_key: ${{ secrets.gc_private_key }}
        gc_client_email: ${{ secrets.gc_client_email }}
        gc_client_id: ${{ secrets.gc_client_id }}
        gc_auth_uri: ${{ secrets.gc_auth_uri }}
        gc_auth_provider_x509_cert_url: ${{ secrets.gc_auth_provider_x509_cert_url }}
        gc_client_x509_cert_url: ${{ secrets.gc_client_x509_cert_url }}
    - name: Publish artifacts from out directory
      uses: actions/upload-artifact@v2
      with:
        name: out
        path: out
  deploy:
    name: Deploy the site
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: out
          path: out
      - name: Debug Files
        run: ls
      - name: Upload to FTP
        uses: isthatcentered/dist-to-ftp@master
        with:
          user: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          host: ${{ secrets.ftp_host }}
          port: ${{ secrets.ftp_port }} # optional, defaults to 21
          path: out # Folder to deploy
          into: iwi-website # Where to place the files in your ftp
          cleanupExisting: true # (Optional), Remove already existing files inside destination folder
